"""add_exp_fields_in_user_table

Revision ID: 0d9644e245fe
Revises: 7ca7a6397d11
Create Date: 2025-11-09 19:35:03.688417

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d9644e245fe"
down_revision: Union[str, None] = "7ca7a6397d11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "users",
        sa.Column("level", sa.Integer(), nullable=False, default=0, server_default="0"),
    )
    op.add_column(
        "users",
        sa.Column(
            "current_exp", sa.Integer(), nullable=False, default=0, server_default="0"
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "total_exp", sa.Integer(), nullable=False, default=0, server_default="0"
        ),
    )
    op.create_index(op.f("ix_users_level"), "users", ["level"], unique=False)
    op.create_index(op.f("ix_users_total_exp"), "users", ["total_exp"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_total_exp"), table_name="users")
    op.drop_index(op.f("ix_users_level"), table_name="users")
    op.drop_column("users", "total_exp")
    op.drop_column("users", "current_exp")
    op.drop_column("users", "level")
    # ### end Alembic commands ###
