"""update subs plan

Revision ID: 109a28fac9bc
Revises: f468b5ccc43b
Create Date: 2025-09-22 19:19:01.962693

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "109a28fac9bc"
down_revision: Union[str, None] = "f468b5ccc43b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

plan_type_enum = sa.Enum("premium", "premium_plus", "ultra", name="plan_type_enum")


def upgrade() -> None:
    """Upgrade schema."""

    plan_type_enum.create(op.get_bind(), checkfirst=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription_plans",
        sa.Column(
            "plan_type",
            plan_type_enum,
            server_default="premium",
            nullable=False,
        ),
    )
    op.add_column(
        "subscription_plans",
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "subscription_plans",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
    )
    op.create_index(
        op.f("ix_subscription_plans_plan_type"),
        "subscription_plans",
        ["plan_type"],
        unique=True,
    )
    op.drop_column("subscription_plans", "bonuses")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription_plans",
        sa.Column(
            "bonuses",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(
        op.f("ix_subscription_plans_plan_type"), table_name="subscription_plans"
    )
    op.drop_column("subscription_plans", "is_active")
    op.drop_column("subscription_plans", "features")
    op.drop_column("subscription_plans", "plan_type")
    plan_type_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
