"""upd user subs table v2

Revision ID: 2d8e6de35b56
Revises: e57887bc8f82
Create Date: 2025-09-25 14:18:17.503328

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d8e6de35b56"
down_revision: Union[str, None] = "e57887bc8f82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


payment_status_type = sa.Enum(
    "succeeded", "waiting_for_capture", "canceled", name="payment_status_type"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    payment_status_type.create(op.get_bind(), checkfirst=False)
    op.add_column(
        "subscription_plans",
        sa.Column("duration_days", sa.Integer(), nullable=False, server_default="30"),
    )
    op.drop_index(
        op.f("ix_subscription_plans_plan_type"), table_name="subscription_plans"
    )
    op.create_index(
        op.f("ix_subscription_plans_plan_type"),
        "subscription_plans",
        ["plan_type"],
        unique=False,
    )
    op.add_column(
        "user_subscriptions",
        sa.Column(
            "payment_status",
            payment_status_type,
            server_default="waiting_for_capture",
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_user_subscriptions_payment_status"),
        "user_subscriptions",
        ["payment_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    payment_status_type.drop(op.get_bind(), checkfirst=False)
    op.drop_index(
        op.f("ix_user_subscriptions_payment_status"), table_name="user_subscriptions"
    )
    op.drop_column("user_subscriptions", "payment_status")
    op.drop_index(
        op.f("ix_subscription_plans_plan_type"), table_name="subscription_plans"
    )
    op.create_index(
        op.f("ix_subscription_plans_plan_type"),
        "subscription_plans",
        ["plan_type"],
        unique=True,
    )
    op.drop_column("subscription_plans", "duration_days")
    # ### end Alembic commands ###
