"""feat chats tables

Revision ID: 34d9491ac7bd
Revises: eed04453d769
Create Date: 2025-09-12 14:14:49.612783

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34d9491ac7bd"
down_revision: Union[str, None] = "eed04453d769"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_messages_recipient_id_users"), "messages", type_="foreignkey"
    )
    op.drop_column("messages", "recipient_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column("recipient_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_messages_recipient_id_users"),
        "messages",
        "users",
        ["recipient_id"],
        ["id"],
    )
    # ### end Alembic commands ###
