"""update mark table

Revision ID: 478faf171c85
Revises: 4a5b9f031b3d
Create Date: 2025-05-21 11:13:12.659512

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "478faf171c85"
down_revision: Union[str, None] = "4a5b9f031b3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    typemark = postgresql.ENUM("game", "other", name="typemark")
    typemark.create(op.get_bind(), checkfirst=True)
    op.add_column("marks", sa.Column("photo", sa.String(length=256), nullable=True))
    op.add_column(
        "marks",
        sa.Column(
            "type_mark",
            sa.Enum("game", "other", name="typemark"),
            server_default="other",
            nullable=False,
        ),
    )
    op.add_column(
        "marks", sa.Column("additional_info", sa.String(length=256), nullable=True)
    )
    op.create_index(
        "idx_locations_geom", "marks", ["geom"], unique=False, postgresql_using="gist"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_locations_geom", table_name="marks", postgresql_using="gist")
    op.drop_column("marks", "additional_info")
    op.drop_column("marks", "type_mark")
    op.drop_column("marks", "photo")
    typemark = postgresql.ENUM("game", "other", name="typemark")
    typemark.drop(op.get_bind())
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    # ### end Alembic commands ###
