"""create user sub

Revision ID: 74783b76d645
Revises: 109a28fac9bc
Create Date: 2025-09-24 18:20:26.354269

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74783b76d645"
down_revision: Union[str, None] = "109a28fac9bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_subscriptions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("end_at", sa.DateTime(), nullable=False),
        sa.Column(
            "starts_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("payment_provider_id", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["subscription_plans.id"],
            name=op.f("fk_user_subscriptions_plan_id_subscription_plans"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_subscriptions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_subscriptions")),
    )
    op.create_index(
        op.f("ix_user_subscriptions_expires_at"),
        "user_subscriptions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_subscriptions_is_active"),
        "user_subscriptions",
        ["is_active"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_subscriptions_is_active"), table_name="user_subscriptions"
    )
    op.drop_index(
        op.f("ix_user_subscriptions_expires_at"), table_name="user_subscriptions"
    )
    op.drop_table("user_subscriptions")
    # ### end Alembic commands ###
