"""feat_gamefication_tables

Revision ID: 7ca7a6397d11
Revises: 2d8e6de35b56
Create Date: 2025-11-09 19:20:04.702035

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ca7a6397d11"
down_revision: Union[str, None] = "2d8e6de35b56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bases")),
    )
    op.create_table(
        "exp_actions",
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("base_exp", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_repeatable", sa.Boolean(), nullable=False),
        sa.Column("max_per_day", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exp_actions")),
    )
    op.create_index(
        op.f("ix_exp_actions_action_type"), "exp_actions", ["action_type"], unique=True
    )
    op.create_table(
        "levels",
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("required_exp", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "required_exp >= 0", name=op.f("ck_levels_check_positive_exp")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_levels")),
    )
    op.create_index(op.f("ix_levels_level"), "levels", ["level"], unique=True)
    op.create_index(
        "ix_levels_level_active", "levels", ["level", "is_active"], unique=False
    )
    op.create_table(
        "user_exp_historys",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("action_id", sa.Integer(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("base_exp", sa.Integer(), nullable=False),
        sa.Column("multiplier", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("total_exp", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_reason", sa.String(length=255), nullable=True),
        sa.Column("level_before", sa.Integer(), nullable=False),
        sa.Column("level_after", sa.Integer(), nullable=False),
        sa.Column("exp_before", sa.Integer(), nullable=False),
        sa.Column("subscription_plan_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "multiplier > 0",
            name=op.f("ck_user_exp_historys_check_positive_multiplier"),
        ),
        sa.CheckConstraint(
            "total_exp >= 0", name=op.f("ck_user_exp_historys_check_positive_total")
        ),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["exp_actions.id"],
            name=op.f("fk_user_exp_historys_action_id_exp_actions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_plan_id"],
            ["subscription_plans.id"],
            name=op.f("fk_user_exp_historys_subscription_plan_id_subscription_plans"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_exp_historys_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_exp_historys")),
    )
    op.create_index(
        "ix_exp_hist_level_up",
        "user_exp_historys",
        ["user_id", "level_after"],
        unique=False,
        postgresql_where=sa.text("level_before != level_after"),
    )
    op.create_index(
        "ix_exp_hist_source",
        "user_exp_historys",
        ["source_type", "source_id"],
        unique=False,
    )
    op.create_index(
        "ix_exp_hist_subscription",
        "user_exp_historys",
        ["subscription_plan_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_exp_hist_user_action_date",
        "user_exp_historys",
        ["user_id", "action_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("is_revoked = false"),
    )
    op.create_index(
        "ix_exp_hist_user_active",
        "user_exp_historys",
        ["user_id", "is_revoked", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_exp_historys_action_id"),
        "user_exp_historys",
        ["action_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_exp_historys_source_type"),
        "user_exp_historys",
        ["source_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_exp_historys_subscription_plan_id"),
        "user_exp_historys",
        ["subscription_plan_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_exp_historys_user_id"),
        "user_exp_historys",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_exp_historys_user_id"), table_name="user_exp_historys")
    op.drop_index(
        op.f("ix_user_exp_historys_subscription_plan_id"),
        table_name="user_exp_historys",
    )
    op.drop_index(
        op.f("ix_user_exp_historys_source_type"), table_name="user_exp_historys"
    )
    op.drop_index(
        op.f("ix_user_exp_historys_action_id"), table_name="user_exp_historys"
    )
    op.drop_index("ix_exp_hist_user_active", table_name="user_exp_historys")
    op.drop_index(
        "ix_exp_hist_user_action_date",
        table_name="user_exp_historys",
        postgresql_where=sa.text("is_revoked = false"),
    )
    op.drop_index("ix_exp_hist_subscription", table_name="user_exp_historys")
    op.drop_index("ix_exp_hist_source", table_name="user_exp_historys")
    op.drop_index(
        "ix_exp_hist_level_up",
        table_name="user_exp_historys",
        postgresql_where=sa.text("level_before != level_after"),
    )
    op.drop_table("user_exp_historys")
    op.drop_index("ix_levels_level_active", table_name="levels")
    op.drop_index(op.f("ix_levels_level"), table_name="levels")
    op.drop_table("levels")
    op.drop_index(op.f("ix_exp_actions_action_type"), table_name="exp_actions")
    op.drop_table("exp_actions")
    op.drop_table("bases")
    # ### end Alembic commands ###
