"""add user metrics

Revision ID: 8ad003ff5c8d
Revises: 4aae0208db9f
Create Date: 2025-11-25 17:50:00.546648

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ad003ff5c8d"
down_revision: Union[str, None] = "4aae0208db9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_metrics",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("total_marks", sa.Integer(), server_default="0", nullable=False),
        sa.Column("active_marks", sa.Integer(), server_default="0", nullable=False),
        sa.Column("ended_marks", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_metrics_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_metrics")),
    )
    op.create_index(
        op.f("ix_user_metrics_user_id"), "user_metrics", ["user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_metrics_user_id"), table_name="user_metrics")
    op.drop_table("user_metrics")
    # ### end Alembic commands ###
