"""add geohash in Mark

Revision ID: b0ed2f68d830
Revises: 4fff75115a36
Create Date: 2025-08-19 12:11:39.312612

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0ed2f68d830"
down_revision: Union[str, None] = "4fff75115a36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column("marks", sa.Column("geohash", sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("marks", "geohash")
    # ### end Alembic commands ###
