"""add unban cols

Revision ID: b8a03d306d30
Revises: d482ab9122cd
Create Date: 2025-09-09 09:16:26.307609

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8a03d306d30"
down_revision: Union[str, None] = "d482ab9122cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users_bans", sa.Column("unbanned_at", sa.DateTime(), nullable=True))
    op.add_column("users_bans", sa.Column("unbanned_by", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_users_bans_unbanned_by_users"),
        "users_bans",
        "users",
        ["unbanned_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_users_bans_unbanned_by_users"), "users_bans", type_="foreignkey"
    )
    op.drop_column("users_bans", "unbanned_by")
    op.drop_column("users_bans", "unbanned_at")
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name=op.f("spatial_ref_sys_srid_check")
        ),
        sa.PrimaryKeyConstraint("srid", name=op.f("spatial_ref_sys_pkey")),
    )
    # ### end Alembic commands ###
