"""upd user table

Revision ID: cab67ffa1191
Revises: 478faf171c85
Create Date: 2025-05-25 02:02:44.448432

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cab67ffa1191"
down_revision: Union[str, None] = "478faf171c85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column("users", sa.Column("phone", sa.String(length=32), nullable=False))
    op.add_column("users", sa.Column("username", sa.String(length=32), nullable=False))
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)
    op.create_unique_constraint(op.f("uq_users_username"), "users", ["username"])
    op.drop_column("users", "first_name")
    op.drop_column("users", "last_name")
    op.drop_column("users", "middle_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "middle_name", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "last_name", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "first_name", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(op.f("uq_users_username"), "users", type_="unique")
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_column("users", "username")
    op.drop_column("users", "phone")
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    # ### end Alembic commands ###
