"""feat chats tables

Revision ID: eed04453d769
Revises: e5362a55ddfb
Create Date: 2025-09-12 13:25:19.337257

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eed04453d769"
down_revision: Union[str, None] = "e5362a55ddfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chats")),
    )
    op.create_table(
        "chat_participants",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"], ["chats.id"], name=op.f("fk_chat_participants_chat_id_chats")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_chat_participants_user_id_users")
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "chat_id", name=op.f("pk_chat_participants")
        ),
    )
    op.add_column("messages", sa.Column("chat_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("fk_messages_chat_id_chats"), "messages", "chats", ["chat_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_messages_chat_id_chats"), "messages", type_="foreignkey"
    )
    op.drop_column("messages", "chat_id")
    op.drop_table("chat_participants")
    op.drop_table("chats")
    # ### end Alembic commands ###
