"""create category and upd exists

Revision ID: f08f176e3bdf
Revises: cab67ffa1191
Create Date: 2025-05-30 00:06:23.738046

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f08f176e3bdf"
down_revision: Union[str, None] = "cab67ffa1191"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("category_name", sa.String(length=64), nullable=False),
        sa.Column("color", sa.String(length=32), nullable=True),
        sa.Column("icon", sa.String(length=128), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("category_name", name=op.f("uq_categories_category_name")),
    )
    # op.drop_table('spatial_ref_sys')
    op.add_column("marks", sa.Column("category_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("fk_marks_category_id_categories"),
        "marks",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("marks", "type_mark")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "marks",
        sa.Column(
            "type_mark",
            postgresql.ENUM("game", "other", name="typemark"),
            server_default=sa.text("'other'::typemark"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("fk_marks_category_id_categories"), "marks", type_="foreignkey"
    )
    op.drop_column("marks", "category_id")
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    op.drop_table("categories")
    # ### end Alembic commands ###
