"""add color level

Revision ID: f1ca736741e8
Revises: 8ad003ff5c8d
Create Date: 2025-11-28 23:10:33.578142

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1ca736741e8"
down_revision: Union[str, None] = "8ad003ff5c8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("levels", sa.Column("color", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("levels", "color")
    # ### end Alembic commands ###
