
name: First CI


on:
  push:
    branches: [main]

env:
  DOCKER_COMPOSE_FILE: "docker-compose.yml"
  PROJECT_DIR: "/root/RealTime-Map_backend"  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t backend_app .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Running tests..."

  deploy:
    environment: production
    needs: [build, test] 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy files to server via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: ${{ env.PROJECT_DIR }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.PROJECT_DIR }}
            docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} down
            docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} pull
            docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d
            docker system prune -f 