name: Build and Deploy with Docker Compose

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: /home/admin/RealTime-map_backend

      - name: Set up Docker Compose
        run: |
          docker compose up --build -d
