name: Build and Deploy with Docker Compose

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env
        run: echo

      - name: Set up Docker Compose
        run: |
          docker system prune -f
          docker compose up --build -d
