name: Build and Deploy with Docker Compose

on:
  push:
    branches: [ "main" ]  # Укажи свою ветку (например, master, dev и т. д.)

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Использует ваш собственный runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Docker Compose
        run: |
          docker-compose down  realtime-map-backend
          docker-compose up --build -d